// Simple i18n - no dependencies needed
import { useState, useEffect } from 'react';

const STORAGE_KEY = 'lang';

// Get initial language: URL param → Hostname → stored preference → browser → default
function getInitialLang() {
  if (typeof window === 'undefined') return 'en';

  // 1. URL Query Parameter (?lang=de) - Highest priority override
  const urlParams = new URLSearchParams(window.location.search);
  const langParam = urlParams.get('lang');
  if (langParam === 'en' || langParam === 'de') {
    localStorage.setItem(STORAGE_KEY, langParam);
    return langParam;
  }

  // 2. Hostname Detection (.de domain) - Zero-config localization
  if (window.location.hostname.endsWith('.de')) {
    return 'de';
  }

  // 3. Stored Preference
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored === 'en' || stored === 'de') return stored;

  // 4. Browser Language Detection
  return navigator.language?.startsWith('de') ? 'de' : 'en';
}

let currentLang = getInitialLang();

export const getLang = () => currentLang;

export const setLang = (lang) => {
  currentLang = lang;
  localStorage.setItem(STORAGE_KEY, lang);
  window.dispatchEvent(new Event('languagechange'));
};

// All translations in one place
const strings = {
  en: {
    // Header/Hero
    'hero.title.line1': 'Stop Renting.',
    'hero.title.line2': 'Start Owning.',
    'hero.subtitle': "You're paying for 80% bloat. We build you a",
    'hero.subtitle.highlight': 'custom tool',
    'hero.subtitle.end': 'with only the 20% you use. One-time fee. Yours forever.',

    // Search
    'search.placeholder': 'What SaaS are we killing today? (e.g., Salesforce)',
    'search.button': 'Kill It',
    'search.auditing': (tool) => `Auditing ${tool}...`,
    'search.loading.1': 'Connecting to Wrecking Ball...',
    'search.loading.2': 'Scanning Pricing Models...',
    'search.loading.3': 'Identifying Bloat...',
    'search.loading.4': 'Finalizing Audit...',

    // Error states
    'error.title': 'Oops!',
    'error.retry': 'Retry Connection',
    'error.enterManually': 'Enter Manually',
    'error.tryDifferent': 'Try a Different Tool',

    // Manual Entry
    'manual.title': 'Manual Entry',
    'manual.toolName': 'Tool Name',
    'manual.monthlyCost': 'Monthly Cost (USD)',
    'manual.features': 'Features (one per line)',
    'manual.featuresHint': 'Enter each feature on a new line',
    'manual.continue': 'Continue to Audit',
    'manual.cancel': 'Cancel',
    'manual.validation.nameRequired': 'Tool name is required',
    'manual.validation.nameLength': (max) => `Name must be ${max} characters or less`,
    'manual.validation.costRequired': 'Monthly cost is required',
    'manual.validation.costPositive': 'Cost must be a positive number',
    'manual.validation.costMax': (max) => `Cost must be less than $${max.toLocaleString()}`,
    'manual.validation.featuresRequired': 'At least one feature is required',
    'manual.validation.featuresMax': 'Maximum 50 features allowed',

    // Audit
    'audit.found': (tool) => `We found ${tool}.`,
    'audit.instruction': 'Uncheck the features you NEVER use.',
    'audit.teamSize': 'Team Size',
    'audit.users': 'users',
    'audit.coreFeatures': 'Core Features',
    'audit.bloatFeatures': 'Bloat Features',
    'audit.addCustom': 'Add Custom Feature',
    'audit.customPlaceholder': 'e.g., Custom CRM integration',
    'audit.analyzing': 'Analyzing...',
    'audit.add': 'Add',

    // Bleed Calculator
    'bleed.title': 'THE 3-YEAR BLEED',
    'bleed.teamSize': 'Team Size (Users)',
    'bleed.subscriptionPlan': 'Subscription Plan',
    'bleed.pricePerUser': 'Enter price per user / month',
    'bleed.priceMissingHint': "We couldn't find pricing for this tier. Add it to keep the bleed accurate.",
    'bleed.totalRent': (name) => `Total Rent Paid to ${name}`,
    'bleed.note': 'Money gone forever.',
    'bleed.tooMuch': 'Way too much to count.',
    'bleed.freeTier': 'FREE tier - Limited features available',
    'bleed.build.title': 'BUILD IT YOURSELF',
    'bleed.build.cost': 'Estimated Cost',
    'bleed.build.savings': 'Total Savings',
    'bleed.build.roi': 'ROI',
    'bleed.build.months': 'months',
    'bleed.build.weeks': 'weeks',

    // Quote Generator
    'quote.title': 'SaaSKiller Solution',
    'quote.oneTime': 'One-Time Fee',
    'quote.includes': (active, custom) => `Includes custom build, ${active} features${custom > 0 ? `, plus ${custom} custom AI add-ons` : ''}, and data ownership.`,
    'quote.disclaimer': '* Estimate based on realistic development time. Final price subject to scoping call. Includes 1st month maintenance.',
    'quote.cta': 'Kill the Rent. Own the Code.',
    'quote.features.kept': 'FEATURES YOU KEEP',
    'quote.features.removed': 'BLOAT YOU CUT',
    'quote.features.custom': 'CUSTOM FEATURES',
    'quote.continue': 'Continue to Results',

    // Audit Checklist
    'audit.coreTitle': 'Core Features',
    'audit.bloatyTitle': 'Bloaty Features',
    'audit.bloatKilled': (pct) => `${pct}% of features that are bloat killed`,
    'audit.showMore': (count, type) => `Show ${count} more ${type} features`,
    'audit.showLess': 'Show less',
    'audit.customTitle': 'Add Custom "Vibe" Features',
    'audit.customInputPlaceholder': '+ Add custom AI workflow...',
    'audit.selectAll': '[+]',
    'audit.deselectAll': '[-]',
    'audit.features': 'features',
    'audit.bloatBadge': 'Bloat',
    'audit.estimateLabel': '(est.)',

    // Results
    'results.title': 'Great Choice.',
    'results.savings': (amount) => `You could save $${amount} over the next 3 years.`,
    'results.form.title': 'Where should we send your official quote?',
    'results.form.name': 'Full Name',
    'results.form.namePlaceholder': 'John Doe',
    'results.form.email': 'Email Address',
    'results.form.emailPlaceholder': 'you@company.com',
    'results.form.submit': 'Get My Sovereign Software Quote',
    'results.form.submitting': 'Sending...',
    'results.form.note': 'No spam. Just a PDF with specs and a contract.',
    'results.success.title': 'Report Sent!',
    'results.success.message': 'Check your email for your detailed audit report PDF.',
    'results.backToAudit': 'Back to Audit',

    // Navigation
    'nav.auditTool': 'Audit Tool',
    'nav.browse': 'Browse Tools',
    'nav.pricing': 'Pricing',
    'nav.getStarted': 'Get Started',

    // CTA
    'cta.kill': 'Kill that SaaS!',

    // Footer
    'footer.copyright': '© 2025 SaaSKiller. All rights reserved.',
    'footer.tagline': 'Built with ♥ and Vibe Coding.',
    'footer.impressum': 'Impressum',
    'footer.datenschutz': 'Datenschutz',
    'legal.lastUpdated': 'Last Updated',
    'legal.backToHome': 'Back to Home',

    // Tool Browser
    'browser.title': 'Browse SaaS Tools',
    'browser.subtitle': 'Explore our database of analyzed SaaS tools and their alternatives.',
    'browser.search': 'Search tools...',
    'browser.all': 'All',
    'browser.noResults': 'No tools found matching your criteria.',
    'browser.perMonth': '/month',
    'browser.features': 'features',
    'browser.viewDetails': 'View Details',
    'browser.showing': (count, total) => `Showing ${count} of ${total} tools`,
    'browser.matching': (query) => `matching "${query}"`,
    'browser.page': (current, total) => `Page ${current} of ${total}`,
    'browser.previous': 'Previous',
    'browser.next': 'Next',
    'browser.analyzePrompt': 'Want us to analyze it with AI?',
    'browser.analyzeButton': (query) => `Analyze ${query} with AI`,
    'browser.analyzeNote': 'This may take 10-20 seconds',
    'browser.noMore': 'No more tools',
    'browser.adjustFilters': 'Try adjusting your filters or going back',
    'browser.clearFilters': 'Clear all filters',
    'browser.notFound': (query) => `"${query}" not found in our database`,
    'browser.noAvailable': 'No tools are available at the moment',

    // Tool Detail
    'detail.backToBrowse': 'Back to Browse',
    'detail.perMonth': '/month',
    'detail.features': 'Features',
    'detail.core': 'Core',
    'detail.bloat': 'Bloat',
    'detail.auditThis': 'Audit This Tool',
    'detail.notFound': 'Tool Not Found',
    'detail.notFoundMessage': "The tool you're looking for doesn't exist.",
    'detail.visitWebsite': 'Visit Website',
    'detail.noFeatures': 'No feature information available for this tool.',
    'detail.plan': 'Plan',
    'featureList.coreDesc': 'Essential features used by most customers',
    'featureList.bloatyDesc': 'Additional features rarely used by most customers',
    'featureList.allShown': (count, type) => `All ${count} ${type} features displayed`,
    'costCalc.title': 'Cost Calculator',
    'costCalc.subtitle': 'Calculate your estimated costs',
    'costCalc.selectedTier': 'Selected Tier',
    'costCalc.teamSizeHint': 'Number of team members (1-1000)',
    'costCalc.billingPeriod': 'Billing Period',
    'costCalc.monthly': 'Monthly',
    'costCalc.yearly': 'Yearly',
    'costCalc.monthlyCost': 'Monthly Cost',
    'costCalc.yearlyCost': 'Yearly Cost',
    'costCalc.equivalent': 'equivalent',
    'costCalc.saveYearly': (pct) => `Save ${pct}% yearly`,
    'costCalc.youSave': (amount) => `You save ${amount} per year by paying annually`,
    'costCalc.annualTotal': (period) => `Annual Total (${period})`,

    // Pricing Page
    'pricing.title': 'Transparent Pricing',
    'pricing.subtitle': 'Estimates based on complexity. Final price locked in after your 1-hour scoping call.',
    'pricing.heroTitle': 'One-Time Fee. Lifetime Ownership.',
    'pricing.heroSubtitle': 'Custom-built tools that do exactly what you need—nothing more, nothing less.',
    'pricing.calcTitle': 'Calculate Your Savings',
    'pricing.calcMonthly': 'Current Monthly Cost (per user)',
    'pricing.calcTeam': 'Team Size',
    'pricing.calcBleed': '3-Year SaaS Cost (The Bleed)',
    'pricing.calcBuild': 'One-Time Build Cost (Example)',
    'pricing.calcYours': 'Yours forever.',
    'pricing.calcYouSave': 'YOU SAVE',
    'pricing.calcBreakeven': (months) => `Breakeven in ${months} months`,
    'pricing.auditCta': 'Start Your Free Audit →',
    'pricing.oneTimePayment': 'One-time payment',
    'pricing.bestFor': (text) => `Best for: ${text}`,
    'pricing.freeQuote': 'Get Free Quote',
    'pricing.howItWorksTitle': 'How It Works',
    'pricing.howItWorksSubtitle': 'From audit to launch in 4 weeks',
    'pricing.step1.title': 'Free Audit',
    'pricing.step1.desc': 'Search your current tool. We analyze features and show you exactly what you pay for vs. what you use.',
    'pricing.step1.time': '15 minutes',
    'pricing.step2.title': 'Scope & Quote',
    'pricing.step2.desc': '1-hour call to understand your needs. We create a product development document with fixed pricing.',
    'pricing.step2.time': '1 hour + 24hr quote',
    'pricing.step3.title': 'Build',
    'pricing.step3.desc': 'Pay 50% to start. We build with AI-assisted development. Weekly check-ins and preview builds.',
    'pricing.step3.time': '3 weeks',
    'pricing.step4.title': 'Launch & Own',
    'pricing.step4.desc': 'We deploy to your server. Pay remaining 50%. Full code handoff. 30-day refinement period.',
    'pricing.step4.time': 'Instant',
    'pricing.starter.name': 'Starter',
    'pricing.starter.desc': 'One-time payment',
    'pricing.starter.price': '$750 - $2.5K',
    'pricing.starter.features': ['3-5 core features', 'Simple UI (forms, tables, dashboards)', 'Mobile-responsive design', '30 days refinement support', 'Full source code ownership'],
    'pricing.starter.bestFor': 'Replacing simple tools like Typeform, Calendly',
    'pricing.pro.name': 'Professional',
    'pricing.pro.desc': 'One-time payment',
    'pricing.pro.price': '$2.5K - $8K',
    'pricing.pro.features': ['5-20 features', 'Custom workflows & automation', 'API integrations (3rd party)', 'Advanced UI components', '90 days support + 2 feature updates', 'Priority tweaks for 1 month'],
    'pricing.pro.bestFor': 'Replacing Airtable, Notion, Monday.com',
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.desc': 'One-time payment',
    'pricing.enterprise.price': '$8K+',
    'pricing.enterprise.features': ['20+ features', 'Complex business logic', 'Multi-role permissions', 'Advanced integrations & webhooks', '12 months support + quarterly planning', 'Dedicated dev team'],
    'pricing.enterprise.bestFor': 'Replacing Salesforce, HubSpot, custom CRMs',
    'pricing.cta': 'Get Started',
    'pricing.popular': 'MOST POPULAR',
    'pricing.includedTitle': "What's Included",
    'pricing.everyBuildTitle': 'Every Build Comes With:',
    'pricing.everyBuildItems': ['Clean, modern UI design', 'Secure authentication & data storage', 'Mobile-responsive', 'Deployment to your cloud', 'Complete source code (MIT license)', 'Documentation', '1st month of hosting included'],
    'pricing.optionalTitle': 'Optional Add-Ons:',
    'pricing.optionalItems': ['Extended support ($200/month)', 'Feature expansions ($150/hour)', 'Priority updates & bug fixes', 'Training sessions', 'White-label reseller license'],
    'pricing.hostingTitle': 'Hosting & Deployment',
    'pricing.hostingDesc': 'We preferably deploy on Hetzner Cloud ($5-$100/month depending on usage). You can also use your own server if preferred.',
    'pricing.compareTitle': 'How We Compare',
    'pricing.compare.header1': 'SaaS Killer',
    'pricing.compare.header2': 'Keep Renting',
    'pricing.compare.header3': 'Traditional Agency',
    'pricing.compare.row1': 'Upfront Cost',
    'pricing.compare.row2': '3-Year Cost',
    'pricing.compare.row3': 'Timeline',
    'pricing.compare.row4': 'Code Ownership',
    'pricing.compare.row5': 'Custom Features',
    'pricing.compare.row6': 'Monthly Fees',
    'pricing.compare.row7': 'Data Control',
    'pricing.compare.row8': 'Surprise Costs',
    'pricing.compare.sometimes': 'Sometimes',
    'pricing.compare.forever': 'Forever',
    'pricing.compare.priceHikes': 'Price hikes',
    'pricing.compare.scopeCreep': 'Scope creep',
    'pricing.compare.immediate': 'Immediate',
    'pricing.compare.vendorCloud': 'Vendor cloud',
    'pricing.compare.payForBloat': 'Pay for bloat',
    'pricing.compare.same': 'Same',
    'pricing.faqTitle': 'Frequently Asked Questions',
    'pricing.faq.q1.q': 'How do you build so fast?',
    'pricing.faq.q1.a': 'We use AI-assisted development (Vibe Coding) that cuts coding time by 75%. What used to take 40 hours now takes 10. This speed lets us offer fixed pricing at a fraction of traditional agency costs.',
    'pricing.faq.q2.q': 'Who owns the code?',
    'pricing.faq.q2.a': 'You do. 100%. MIT license. Do whatever you want with it—modify it, sell it, hire any developer to maintain it. No strings attached.',
    'pricing.faq.q3.q': "What if I don't like it after a week?",
    'pricing.faq.q3.a': "No problem. We offer tweaks and refinements for up to 1 month after delivery. We'll work with you to get it right.",
    'pricing.faq.q4.q': 'What if I need changes later?',
    'pricing.faq.q4.a': "You can hire us at $150/hour or hire any developer—it's your code.",
    'pricing.faq.q5.q': 'Do you handle hosting?',
    'pricing.faq.q5.a': 'We deploy to Hetzner Cloud (preferred) or your own server. Hosting costs $5-$100/month depending on usage. First month included free.',
    'pricing.faq.q6.q': 'What if the build takes longer?',
    'pricing.faq.q6.a': "Fixed-price guarantee. If we quoted $3,000, you pay $3,000—even if it takes us longer. That's our risk, not yours.",
    'pricing.faq.q7.q': 'Can you integrate with other services?',
    'pricing.faq.q7.a': "Most integrations are possible (Stripe, APIs, webhooks, etc.). We'll evaluate during the 1-hour scoping call and include in the quote.",
    'pricing.faq.q8.q': 'How does payment work?',
    'pricing.faq.q8.a': '50% down when you approve the quote to start work. 50% on delivery when we hand over the code and deployment.',
    'pricing.trustTitle': 'No Contracts. No Retainers. No Surprises.',
    'pricing.trust.price.title': 'Fixed Price Guarantee',
    'pricing.trust.price.desc': "You'll know the exact cost before we write a single line of code.",
    'pricing.trust.code.title': 'Code Ownership',
    'pricing.trust.code.desc': 'MIT license. Your intellectual property. No strings.',
    'pricing.trust.time.title': '1-Month Refinements',
    'pricing.trust.time.desc': "Don't like something? We'll tweak it for up to a month after delivery.",
    'pricing.trust.process.title': 'Transparent Process',
    'pricing.trust.process.desc': 'Weekly demos. Direct Slack access. See progress in real-time.',
    'pricing.finalTitle': 'Stop Bleeding Cash. Start Building Equity.',
    'pricing.finalSubtitle': 'Get your free quote. No commitment required.',
    'pricing.browseLibrary': 'browse our library',
    'pricing.browseSuffix': 'of 100+ pre-analyzed SaaS tools',
    'pricing.vs': 'vs',
    'browser.from': 'From',
    'browser.noDescription': 'No description available',
    'filter.loading': 'Loading categories...',
    'filter.title': 'Filter by Category',
    'filter.clear': 'Clear filter',
    'filter.showing': (name) => `Showing tools in ${name}`,
    'filter.allCategories': 'All categories',
    'search.clear': 'Clear search',

    // Categories
    'category.communication': 'Communication',
    'category.productivity': 'Productivity',
    'category.development': 'Development',
    'category.design': 'Design',
    'category.marketing': 'Marketing',
    'category.sales-crm': 'Sales & CRM',
    'category.analytics': 'Analytics',
    'category.project-management': 'Project Management',
    'category.finance': 'Finance',
    'category.hr-recruiting': 'HR & Recruiting',

    // Tier pricing strings (tierPricing utility)
    'tier.priceMissing': 'Price missing',
    'tier.free': 'Free',
    'tier.perMonthShort': '/mo',
    'tier.perUser': 'per user',
    'tier.enterpriseMessage.0': 'Too Much To Count',
    'tier.enterpriseMessage.1': 'You need some serious help',
    'tier.enterpriseMessage.2': 'If you have to ask...',
    'tier.enterpriseMessage.3': 'More than your car payment',
    'tier.enterpriseMessage.4': 'Call them. We dare you.',
    'pricing.or': 'Or',
  },

  de: {
    // Header/Hero
    'hero.title.line1': 'Schluss mit Mieten.',
    'hero.title.line2': 'Anfangen zu Besitzen.',
    'hero.subtitle': 'Du zahlst für 80% Ballast. Wir bauen dir ein',
    'hero.subtitle.highlight': 'individuelles Tool',
    'hero.subtitle.end': 'mit nur den 20%, die du nutzt. Einmalzahlung. Für immer deins.',

    // Search
    'search.placeholder': 'Welches SaaS killen wir heute? (z.B. Salesforce)',
    'search.button': 'Killen',
    'search.auditing': (tool) => `Analysiere ${tool}...`,
    'search.loading.1': 'Verbinde mit Wrecking Ball...',
    'search.loading.2': 'Scanne Preismodelle...',
    'search.loading.3': 'Identifiziere Ballast...',
    'search.loading.4': 'Finalisiere Audit...',

    // Error states
    'error.title': 'Ups!',
    'error.retry': 'Erneut versuchen',
    'error.enterManually': 'Manuell eingeben',
    'error.tryDifferent': 'Anderes Tool versuchen',

    // Manual Entry
    'manual.title': 'Manuelle Eingabe',
    'manual.toolName': 'Tool-Name',
    'manual.monthlyCost': 'Monatliche Kosten (EUR)',
    'manual.features': 'Funktionen (eine pro Zeile)',
    'manual.featuresHint': 'Gib jede Funktion in einer neuen Zeile ein',
    'manual.continue': 'Weiter zum Audit',
    'manual.cancel': 'Abbrechen',
    'manual.validation.nameRequired': 'Tool-Name ist erforderlich',
    'manual.validation.nameLength': (max) => `Name darf maximal ${max} Zeichen haben`,
    'manual.validation.costRequired': 'Monatliche Kosten sind erforderlich',
    'manual.validation.costPositive': 'Kosten müssen positiv sein',
    'manual.validation.costMax': (max) => `Kosten müssen unter ${max.toLocaleString()} € liegen`,
    'manual.validation.featuresRequired': 'Mindestens eine Funktion erforderlich',
    'manual.validation.featuresMax': 'Maximal 50 Funktionen erlaubt',

    // Audit
    'audit.found': (tool) => `Wir haben ${tool} gefunden.`,
    'audit.instruction': 'Deaktiviere die Funktionen, die du NIE nutzt.',
    'audit.teamSize': 'Teamgröße',
    'audit.users': 'Benutzer',
    'audit.coreFeatures': 'Kernfunktionen',
    'audit.bloatFeatures': 'Ballast-Funktionen',
    'audit.addCustom': 'Eigene Funktion hinzufügen',
    'audit.customPlaceholder': 'z.B. Individuelle CRM-Integration',
    'audit.analyzing': 'Analysiere...',
    'audit.add': 'Hinzufügen',

    // Bleed Calculator
    'bleed.title': 'DER 3-JAHRES-VERLUST',
    'bleed.teamSize': 'Teamgröße (Benutzer)',
    'bleed.subscriptionPlan': 'Abo-Tarif',
    'bleed.pricePerUser': 'Preis pro Benutzer / Monat eingeben',
    'bleed.priceMissingHint': 'Wir konnten keinen Preis für diesen Tarif finden. Gib ihn ein, um den Verlust korrekt zu berechnen.',
    'bleed.totalRent': (name) => `Gesamte Miete an ${name}`,
    'bleed.note': 'Geld für immer verloren.',
    'bleed.tooMuch': 'Viel zu viel zum Zählen.',
    'bleed.freeTier': 'KOSTENLOS - Eingeschränkte Funktionen',
    'bleed.build.title': 'SELBST ENTWICKELN',
    'bleed.build.cost': 'Geschätzte Kosten',
    'bleed.build.savings': 'Gesamtersparnis',
    'bleed.build.roi': 'Amortisation',
    'bleed.build.months': 'Monate',
    'bleed.build.weeks': 'Wochen',

    // Quote Generator
    'quote.title': 'SaaSKiller-Lösung',
    'quote.oneTime': 'Einmalzahlung',
    'quote.includes': (active, custom) => `Inklusive individuellem Build, ${active} Funktionen${custom > 0 ? `, plus ${custom} individuelle KI-Add-ons` : ''} und Datenhoheit.`,
    'quote.disclaimer': '* Schätzung basierend auf realistischer Entwicklungszeit. Endpreis nach Scoping-Gespräch. Inkl. 1. Monat Wartung.',
    'quote.cta': 'Schluss mit Miete. Besitze den Code.',
    'quote.features.kept': 'FUNKTIONEN, DIE DU BEHÄLTST',
    'quote.features.removed': 'BALLAST, DEN DU STREICHST',
    'quote.features.custom': 'EIGENE FUNKTIONEN',
    'quote.continue': 'Weiter zu den Ergebnissen',

    // Audit Checklist
    'audit.coreTitle': 'Kernfunktionen',
    'audit.bloatyTitle': 'Ballast-Funktionen',
    'audit.bloatKilled': (pct) => `${pct}% der Ballast-Funktionen entfernt`,
    'audit.showMore': (count, type) => `${count} weitere ${type}-Funktionen anzeigen`,
    'audit.showLess': 'Weniger anzeigen',
    'audit.customTitle': 'Eigene "Vibe"-Funktionen hinzufügen',
    'audit.customInputPlaceholder': '+ Eigenen KI-Workflow hinzufügen...',
    'audit.selectAll': '[+]',
    'audit.deselectAll': '[-]',
    'audit.features': 'Funktionen',
    'audit.bloatBadge': 'Ballast',
    'audit.estimateLabel': '(gesch.)',

    // Results
    'results.title': 'Gute Wahl.',
    'results.savings': (amount) => `Du könntest ${amount} € über die nächsten 3 Jahre sparen.`,
    'results.form.title': 'Wohin sollen wir dein offizielles Angebot senden?',
    'results.form.name': 'Vollständiger Name',
    'results.form.namePlaceholder': 'Max Mustermann',
    'results.form.email': 'E-Mail-Adresse',
    'results.form.emailPlaceholder': 'du@firma.de',
    'results.form.submit': 'Mein Software-Angebot erhalten',
    'results.form.submitting': 'Wird gesendet...',
    'results.form.note': 'Kein Spam. Nur ein PDF mit Spezifikationen und Vertrag.',
    'results.success.title': 'Bericht gesendet!',
    'results.success.message': 'Prüfe dein Postfach für deinen detaillierten Audit-Bericht.',
    'results.backToAudit': 'Zurück zum Audit',

    // Navigation
    'nav.auditTool': 'Audit-Tool',
    'nav.browse': 'Tools durchsuchen',
    'nav.pricing': 'Preise',
    'nav.getStarted': 'Loslegen',

    // CTA
    'cta.kill': 'Jetzt SaaS killen!',

    // Footer
    'footer.copyright': '© 2025 SaaSKiller. Alle Rechte vorbehalten.',
    'footer.tagline': 'Entwickelt mit ♥ und Vibe Coding.',
    'footer.impressum': 'Impressum',
    'footer.datenschutz': 'Datenschutz',
    'legal.lastUpdated': 'Zuletzt aktualisiert',
    'legal.backToHome': 'Zurück zur Startseite',

    // Tool Browser
    'browser.title': 'SaaS-Tools durchsuchen',
    'browser.subtitle': 'Erkunde unsere Datenbank analysierter SaaS-Tools und ihrer Alternativen.',
    'browser.search': 'Tools suchen...',
    'browser.all': 'Alle',
    'browser.noResults': 'Keine Tools gefunden, die deinen Kriterien entsprechen.',
    'browser.perMonth': '/Monat',
    'browser.features': 'Funktionen',
    'browser.viewDetails': 'Details anzeigen',
    'browser.showing': (count, total) => `Zeige ${count} von ${total} Tools`,
    'browser.matching': (query) => `passend zu "${query}"`,
    'browser.page': (current, total) => `Seite ${current} von ${total}`,
    'browser.previous': 'Zurück',
    'browser.next': 'Weiter',
    'browser.analyzePrompt': 'Sollen wir es mit KI analysieren?',
    'browser.analyzeButton': (query) => `${query} mit KI analysieren`,
    'browser.analyzeNote': 'Dies kann 10-20 Sekunden dauern',
    'browser.noMore': 'Keine weiteren Tools',
    'browser.adjustFilters': 'Passe deine Filter an oder gehe zurück',
    'browser.clearFilters': 'Alle Filter löschen',
    'browser.notFound': (query) => `"${query}" nicht in unserer Datenbank gefunden`,
    'browser.noAvailable': 'Momentan sind keine Tools verfügbar',

    // Tool Detail
    'detail.backToBrowse': 'Zurück zur Übersicht',
    'detail.perMonth': '/Monat',
    'detail.features': 'Funktionen',
    'detail.core': 'Kern',
    'detail.bloat': 'Ballast',
    'detail.auditThis': 'Dieses Tool auditieren',
    'detail.notFound': 'Tool nicht gefunden',
    'detail.notFoundMessage': 'Das gesuchte Tool existiert nicht.',
    'detail.visitWebsite': 'Website besuchen',
    'detail.noFeatures': 'Keine Informationen zu Funktionen für dieses Tool verfügbar.',
    'detail.plan': 'Tarif',
    'featureList.coreDesc': 'Wichtige Kernfunktionen für die meisten Kunden',
    'featureList.bloatyDesc': 'Zusatzfunktionen, die selten genutzt werden',
    'featureList.allShown': (count, type) => `Alle ${count} ${type}-Funktionen angezeigt`,
    'costCalc.title': 'Kostenrechner',
    'costCalc.subtitle': 'Berechne deine geschätzten Kosten',
    'costCalc.selectedTier': 'Ausgewählter Tarif',
    'costCalc.teamSizeHint': 'Anzahl der Teammitglieder (1-1000)',
    'costCalc.billingPeriod': 'Abrechnungszeitraum',
    'costCalc.monthly': 'Monatlich',
    'costCalc.yearly': 'Jährlich',
    'costCalc.monthlyCost': 'Monatliche Kosten',
    'costCalc.yearlyCost': 'Jährliche Kosten',
    'costCalc.equivalent': 'entspricht',
    'costCalc.saveYearly': (pct) => `${pct}% jährlich sparen`,
    'costCalc.youSave': (amount) => `Du sparst ${amount} pro Jahr bei jährlicher Zahlung`,
    'costCalc.annualTotal': (period) => `Gesamt pro Jahr (${period})`,

    // Pricing Page
    'pricing.title': 'Transparente Preise',
    'pricing.subtitle': 'Schätzungen basierend auf Komplexität. Endpreis fixiert nach dem 1-stündigen Scoping-Gespräch.',
    'pricing.heroTitle': 'Einmalzahlung. Lebenslanger Besitz.',
    'pricing.heroSubtitle': 'Individuell entwickelte Tools, die genau das tun, was Sie brauchen – nicht mehr und nicht weniger.',
    'pricing.calcTitle': 'Berechnen Sie Ihre Ersparnis',
    'pricing.calcMonthly': 'Aktuelle monatliche Kosten (pro Benutzer)',
    'pricing.calcTeam': 'Teamgröße',
    'pricing.calcBleed': '3-Jahres SaaS-Kosten (Der Verlust)',
    'pricing.calcBuild': 'Einmalige Entwicklungskosten (Beispiel)',
    'pricing.calcYours': 'Für immer deins.',
    'pricing.calcYouSave': 'IHRE ERSPARNIS',
    'pricing.calcBreakeven': (months) => `Amortisation in ${months} Monaten`,
    'pricing.auditCta': 'Kostenloses Audit starten →',
    'pricing.oneTimePayment': 'Einmalige Zahlung',
    'pricing.bestFor': (text) => `Ideal für: ${text}`,
    'pricing.freeQuote': 'Angebot anfordern',
    'pricing.howItWorksTitle': 'So funktioniert es',
    'pricing.howItWorksSubtitle': 'Vom Audit zum Launch in 4 Wochen',
    'pricing.step1.title': 'Kostenloses Audit',
    'pricing.step1.desc': 'Suche dein aktuelles Tool. Wir analysieren die Funktionen und zeigen dir, wofür du zahlst vs. was du nutzt.',
    'pricing.step1.time': '15 Minuten',
    'pricing.step2.title': 'Scope & Angebot',
    'pricing.step2.desc': '1-stündiges Gespräch, um deine Bedürfnisse zu verstehen. Wir erstellen ein Lastenheft mit Festpreis.',
    'pricing.step2.time': '1 Stunde + 24h Angebot',
    'pricing.step3.title': 'Entwicklung',
    'pricing.step3.desc': '50% Anzahlung zum Start. Wir entwickeln mit KI-Unterstützung. Wöchentliche Updates und Vorschau-Builds.',
    'pricing.step3.time': '3 Wochen',
    'pricing.step4.title': 'Launch & Besitz',
    'pricing.step4.desc': 'Wir installieren auf deinem Server. Restliche 50% Zahlung. Vollständige Code-Übergabe. 30 Tage Optimierung.',
    'pricing.step4.time': 'Sofort',
    'pricing.starter.name': 'Starter',
    'pricing.starter.desc': 'Einmalige Zahlung',
    'pricing.starter.price': '750 € - 2.500 €',
    'pricing.starter.features': ['3-5 Kernfunktionen', 'Einfaches UI (Formulare, Tabellen, Dashboards)', 'Mobile-Responsive Design', '30 Tage Support', 'Vollständiges Code-Eigentum'],
    'pricing.starter.bestFor': 'Ersetzt einfache Tools wie Typeform, Calendly',
    'pricing.pro.name': 'Professional',
    'pricing.pro.desc': 'Einmalige Zahlung',
    'pricing.pro.price': '2.500 € - 8.000 €',
    'pricing.pro.features': ['5-20 Funktionen', 'Individuelle Workflows & Automatisierung', 'API-Integrationen (Drittanbieter)', 'Erweiterte UI-Komponenten', '90 Tage Support + 2 Funktions-Updates', 'Prioritäts-Anpassungen für 1 Monat'],
    'pricing.pro.bestFor': 'Ersetzt Airtable, Notion, Monday.com',
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.desc': 'Einmalige Zahlung',
    'pricing.enterprise.price': 'Ab 8.000 €',
    'pricing.enterprise.features': ['20+ Funktionen', 'Komplexe Geschäftslogik', 'Multi-Rollen Berechtigungen', 'Erweiterte Integrationen & Webhooks', '12 Monate Support + Quartalsplanung', 'Dediziertes Entwicklerteam'],
    'pricing.enterprise.bestFor': 'Ersetzt Salesforce, HubSpot, individuelle CRMs',
    'pricing.cta': 'Loslegen',
    'pricing.popular': 'BELIEBTESTE',
    'pricing.includedTitle': 'Was enthalten ist',
    'pricing.everyBuildTitle': 'Jedes Projekt enthält:',
    'pricing.everyBuildItems': ['Modernes UI-Design', 'Sichere Authentifizierung & Datenspeicherung', 'Mobile-Responsive', 'Installation in Ihrer Cloud', 'Vollständiger Quellcode (MIT-Lizenz)', 'Dokumentation', 'Inklusive 1. Monat Hosting'],
    'pricing.optionalTitle': 'Optionale Erweiterungen:',
    'pricing.optionalItems': ['Erweiterter Support (200 €/Monat)', 'Funktionserweiterungen (150 €/Stunde)', 'Prioritäts-Updates & Bugfixes', 'Schulungen', 'White-Label Reseller-Lizenz'],
    'pricing.hostingTitle': 'Hosting & Installation',
    'pricing.hostingDesc': 'Wir installieren bevorzugt in der Hetzner Cloud (5 € - 100 €/Monat je nach Nutzung). Sie können auch Ihren eigenen Server verwenden.',
    'pricing.compareTitle': 'Der Vergleich',
    'pricing.compare.header1': 'SaaS Killer',
    'pricing.compare.header2': 'Weiter Mieten',
    'pricing.compare.header3': 'Klassische Agentur',
    'pricing.compare.row1': 'Einmalige Kosten',
    'pricing.compare.row2': '3-Jahres-Kosten',
    'pricing.compare.row3': 'Zeitplan',
    'pricing.compare.row4': 'Code-Eigentum',
    'pricing.compare.row5': 'Eigene Funktionen',
    'pricing.compare.row6': 'Monatliche Gebühren',
    'pricing.compare.row7': 'Datenkontrolle',
    'pricing.compare.row8': 'Überraschungskosten',
    'pricing.compare.sometimes': 'Teilweise',
    'pricing.compare.forever': 'Für immer',
    'pricing.compare.priceHikes': 'Preiserhöhungen',
    'pricing.compare.scopeCreep': 'Zusatzkosten',
    'pricing.compare.immediate': 'Sofort',
    'pricing.compare.vendorCloud': 'Hersteller-Cloud',
    'pricing.compare.payForBloat': 'Zahlung für Ballast',
    'pricing.compare.same': 'Gleichbleibend',
    'pricing.faqTitle': 'Häufig gestellte Fragen',
    'pricing.faq.q1.q': 'Warum seid ihr so schnell?',
    'pricing.faq.q1.a': 'Wir nutzen KI-gestützte Entwicklung (Vibe Coding), die die Programmierzeit um 75% reduziert. Was früher 40 Stunden dauerte, dauert jetzt 10. Diese Geschwindigkeit ermöglicht uns Festpreise zu einem Bruchteil der Kosten klassischer Agenturen.',
    'pricing.faq.q2.q': 'Wem gehört der Code?',
    'pricing.faq.q2.a': 'Ihnen. Zu 100%. MIT-Lizenz. Sie können damit machen, was Sie wollen – modifizieren, verkaufen, jeden beliebigen Entwickler mit der Wartung beauftragen. Keine Bindung.',
    'pricing.faq.q3.q': 'Was, wenn es mir nach einer Woche nicht gefällt?',
    'pricing.faq.q3.a': 'Kein Problem. Wir bieten Anpassungen und Optimierungen bis zu 1 Monat nach der Lieferung an. Wir arbeiten mit Ihnen zusammen, bis es passt.',
    'pricing.faq.q4.q': 'Was, wenn ich später Änderungen brauche?',
    'pricing.faq.q4.a': 'Sie können uns für 150 €/Stunde buchen oder jeden anderen Entwickler beauftragen – es ist Ihr Code.',
    'pricing.faq.q5.q': 'Kümmert ihr euch um das Hosting?',
    'pricing.faq.q5.a': 'Wir installieren in der Hetzner Cloud (bevorzugt) oder auf Ihrem eigenen Server. Hosting kostet 5 € - 100 €/Monat. Der erste Monat ist kostenlos enthalten.',
    'pricing.faq.q6.q': 'Was, wenn die Entwicklung länger dauert?',
    'pricing.faq.q6.a': 'Festpreisgarantie. Wenn wir 3.000 € angeboten haben, zahlen Sie 3.000 € – auch wenn wir länger brauchen. Das ist unser Risiko, nicht Ihres.',
    'pricing.faq.q7.q': 'Sind Integrationen mit anderen Diensten möglich?',
    'pricing.faq.q7.a': 'Die meisten Integrationen sind möglich (Stripe, APIs, Webhooks etc.). Wir prüfen das im 1-stündigen Scoping-Gespräch und nehmen es in das Angebot auf.',
    'pricing.faq.q8.q': 'Wie funktioniert die Bezahlung?',
    'pricing.faq.q8.a': '50% Anzahlung bei Auftragsbestätigung. 50% bei Lieferung, wenn wir den Code und die Installation übergeben.',
    'pricing.trustTitle': 'Keine Verträge. Keine Fixkosten. Keine Überraschungen.',
    'pricing.trust.price.title': 'Festpreisgarantie',
    'pricing.trust.price.desc': 'Sie kennen die exakten Kosten, bevor wir die erste Zeile Code schreiben.',
    'pricing.trust.code.title': 'Code-Eigentum',
    'pricing.trust.code.desc': 'MIT-Lizenz. Ihr geistiges Eigentum. Keine Verpflichtungen.',
    'pricing.trust.time.title': '1 Monat Optimierung',
    'pricing.trust.time.desc': 'Etwas passt nicht? Wir optimieren es bis zu einen Monat nach Lieferung.',
    'pricing.trust.process.title': 'Transparenter Prozess',
    'pricing.trust.process.desc': 'Wöchentliche Demos. Direkter Slack-Kontakt. Verfolgen Sie den Fortschritt in Echtzeit.',
    'pricing.finalTitle': 'Schluss mit Mietkosten. Aufbau von digitalem Eigentum.',
    'pricing.finalSubtitle': 'Fordern Sie Ihr kostenloses Angebot an. Unverbindlich.',
    'pricing.browseLibrary': 'Bibliothek durchsuchen',
    'pricing.browseSuffix': 'von 100+ analysierten Tools',
    'pricing.vs': 'vs.',
    'browser.from': 'Ab',
    'browser.noDescription': 'Keine Beschreibung verfügbar',
    'filter.loading': 'Kategorien laden...',
    'filter.title': 'Nach Kategorie filtern',
    'filter.clear': 'Filter löschen',
    'filter.showing': (name) => `Zeige Tools in ${name}`,
    'filter.allCategories': 'Alle Kategorien',
    'search.clear': 'Suche löschen',

    // Kategorien
    'category.communication': 'Kommunikation',
    'category.productivity': 'Produktivität',
    'category.development': 'Entwicklung',
    'category.design': 'Design',
    'category.marketing': 'Marketing',
    'category.sales-crm': 'Vertrieb & CRM',
    'category.analytics': 'Analytik',
    'category.project-management': 'Projektmanagement',
    'category.finance': 'Finanzen',
    'category.hr-recruiting': 'HR & Recruiting',

    // Tier-Pricing Strings (tierPricing Utility)
    'tier.priceMissing': 'Preis fehlt',
    'tier.free': 'Kostenlos',
    'tier.perMonthShort': '/Monat',
    'tier.perUser': 'pro Nutzer',
    'tier.enterpriseMessage.0': 'Zu viel zum Zählen',
    'tier.enterpriseMessage.1': 'Da brauchen Sie ernsthafte Hilfe',
    'tier.enterpriseMessage.2': 'Wenn Sie fragen müssen...',
    'tier.enterpriseMessage.3': 'Mehr als Ihre Autokreditrate',
    'tier.enterpriseMessage.4': 'Rufen Sie dort an. Wir trauen uns.',
    'pricing.or': 'Oder',
  }
};

// Translation function
export const t = (key, ...args) => {
  const value = strings[currentLang]?.[key];
  if (typeof value === 'function') return value(...args);
  return value || strings['en']?.[key] || key;
};

// Hook for React components that need to re-render on language change
export const useLang = () => {
  const [, forceUpdate] = useState(0);

  useEffect(() => {
    const handler = () => forceUpdate(n => n + 1);
    window.addEventListener('languagechange', handler);
    return () => window.removeEventListener('languagechange', handler);
  }, []);

  return { lang: currentLang, setLang, t };
};

// Export for backend use
export const getStrings = (lang = 'en') => strings[lang] || strings['en'];
